# Generated by Django 4.1.5 on 2023-01-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.TextField()),
                ("quarter", models.CharField(max_length=10)),
                ("profit", models.DecimalField(decimal_places=2, max_digits=18)),
                ("expected", models.DecimalField(decimal_places=2, max_digits=18)),
                ("submitted", models.BooleanField()),
            ],
        ),
    ]
